name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Dianini"




# name: CI

# on:
#   push:
#     branches: [main]
  
# jobs:
#   CI:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v3.5.3
#       - name: Docker Login
#         uses: docker/login-action@v2.2.0
#         with:
#           username: ${{  secrets.USER  }}
#           password: ${{  secrets.PASSWD  }}
          
#       - name: Build and push Docker images
#         uses: docker/build-push-action@v4.1.1
#         with:
#           context: .
#           push: true
#           tags: |
#             dianini/echocontainer:v1
#             dianini/echocontainer:latest
